networks:
  default:
    name: dev
    external: true
services:
  mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=caching_sha2_password
    container_name: mysql
    environment:
    - MYSQL_DATABASE=docriver
    - MYSQL_USER=${DOCRIVER_MYSQL_USER:-docriver}
    - MYSQL_PASSWORD=${DOCRIVER_MYSQL_PASSWORD:-docriver}
    - MYSQL_ROOT_PASSWORD=${DOCRIVER_MYSQL_ROOT_PASSWORD:-docriver}
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 600s
      test: mysqladmin ping -h mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 5s
    hostname: mysql
    image: mysql:${DOCRIVER_MYSQL_VERSION:-8.2}
    ports:
    - ${DOCRIVER_MYSQL_PORT:-3306}:3306
    restart: on-failure
    volumes:
    - ../mysql:/docker-entrypoint-initdb.d
    - mysqldata:/var/lib/mysql
  minio:
    container_name: minio
    image: quay.io/minio/minio:${DOCRIVER_MINIO_VERSION:-RELEASE.2023-12-23T07-19-11Z.fips}
    command: server /data --console-address ":${DOCRIVER_MINIO_CONSOLE_PORT:-9001}"
    # --sftp="address=:8022"
    # --sftp="ssh-private-key=/home/miniouser/.ssh/id_rsa"
    environment:
      MINIO_BROWSER_REDIRECT_URL: ${DOCRIVER_MINIO_CONSOLE_URL}
    volumes:
    - miniodata:/data
    ports:
    - ${DOCRIVER_MINIO_PORT:-9000}:9000
    - ${DOCRIVER_MINIO_CONSOLE_PORT:-9001}:9001
  clamav:
    container_name: clamav
    image: clamav/clamav:${DOCRIVER_CLAMAV_VERSION:-stable_base}
    volumes:
    - clamavdata:/var/lib/clamav
    - ${DOCRIVER_UNTRUSTED_ROOT:-/}:/scandir
    ports:
    - ${DOCRIVER_CLAMAV_PORT:-3310}:3310
volumes:
  mysqldata: null
  miniodata: null
  clamavdata: null
