version: '3.9'
networks:
  default:
    name: dev
    external: true
services:
  mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=caching_sha2_password
    container_name: mysql
    environment:
    - MYSQL_DATABASE=docriver
    - MYSQL_USER=${DOCRIVER_MYSQL_USER:-docriver}
    - MYSQL_PASSWORD=${DOCRIVER_MYSQL_PASSWORD:-docriver}
    - MYSQL_ROOT_PASSWORD=${DOCRIVER_MYSQL_ROOT_PASSWORD:-docriver}
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 600s
      test: mysqladmin ping -h mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 5s
    hostname: mysql
    image: mysql:${DOCRIVER_MYSQL_VERSION:-8.2}
    ports:
    - ${DOCRIVER_MYSQL_PORT:-3306}:3306
    restart: on-failure
    volumes:
    - ../mysql:/docker-entrypoint-initdb.d
    - mysqldata:/var/lib/mysql
  minio:
    container_name: minio
    image: quay.io/minio/minio:${DOCRIVER_MINIO_VERSION:-RELEASE.2023-12-23T07-19-11Z.fips}
    command: server /data --console-address ":${DOCRIVER_MINIO_CONSOLE_PORT:-9001}"
    # --sftp="address=:8022"
    # --sftp="ssh-private-key=/home/miniouser/.ssh/id_rsa"
    environment:
      MINIO_BROWSER_REDIRECT_URL: ${DOCRIVER_MINIO_CONSOLE_URL}
    volumes:
    - miniodata:/data
    ports:
    - ${DOCRIVER_MINIO_PORT:-9000}:9000
    - ${DOCRIVER_MINIO_CONSOLE_PORT:-9001}:9001
  clamav:
    container_name: clamav
    image: clamav/clamav:${DOCRIVER_CLAMAV_VERSION:-stable_base}
    volumes:
    - clamavdata:/var/lib/clamav
    - ${DOCRIVER_UNTRUSTED_ROOT:-/}:/scandir
    ports:
    - ${DOCRIVER_CLAMAV_PORT:-3310}:3310
  # keycloak:
  #     container_name: keycloak
  #     image: quay.io/keycloak/keycloak:24.0.4
  #     environment:
  #       KC_DB: mysql
  #       KC_DB_URL_HOST: mysql
  #       KC_DB_SCHEMA: keycloak
  #       KC_DB_USERNAME: keycloak
  #       KC_DB_PASSWORD: keycloak
  #       KEYCLOAK_ADMIN: admin
  #       KEYCLOAK_ADMIN_PASSWORD: admin
  #       KC_HOSTNAME_STRICT: "false"
  #       KC_HTTP_RELATIVE_PATH: "/keycloak"
  #       KC_PROXY: "edge"
  #     ports:
  #       - 18080:8080
  #       - 18443:8443 
  #     depends_on:
  #       - mysql
  #     command: "start-dev --proxy-headers=xforwarded --hostname-strict=false --hostname-strict-https=false --hostname-url=https://keycloak:8443/keycloak"
  gateway:
    container_name: docriver-gateway
    image: docriver-base:0.0.1-SNAPSHOT
    depends_on:
      mysql:
        condition: service_healthy
        # restart: true
      minio:
        condition: service_started
        # restart: true
      clamav:
        condition: service_started
        # restart: true
    user: 1000:1000
    volumes:
    - ${DOCRIVER_GW_HOME}/src:/app
    - ${HOME}/.ssh/docriver:/keystore
    - ${HOME}/storage/docriver/raw:/raw
    - ${HOME}/storage/docriver/untrusted:/untrusted
    command: ["python", "/app/gateway.py", "--authKeystore", "/keystore/truststore.p12", "--authPassword", "docriver", "--rawFilesystemMount", "/raw", "--untrustedFilesystemMount", "/untrusted", "--dbHost", "mysql", "--scanHost", "clamav", "--objUrl", "minio:9000", "--tlsKey", "/keystore/docriver.key", "--tlsCert", "/keystore/docriver.crt", "--log", "INFO", "--debug"]
    ports:
    - 8443:5000
volumes:
  mysqldata: null
  miniodata: null
  clamavdata: null
