networks:
  default:
    name: dev
    external: true
services:
  opentel-collector:
    image: otel/opentelemetry-collector-contrib:${DOCRIVER_OPENTEL_COLLECTOR_VERSION:-0.109.0}
    volumes:
    - ${DOCRIVER_GW_HOME}/infrastructure/opentel-collector/collector-config.yaml:/etc/otelcol/config.yaml
    environment:
      - DOCRIVER_OPENTEL_EXPORT_ENDPOINT=${DOCRIVER_OPENTEL_EXPORT_ENDPOINT:-localhost:4317}
      - DOCRIVER_OPENTEL_EXPORT_ENDPOINT_AUTH_VAL=${DOCRIVER_OPENTEL_EXPORT_ENDPOINT_AUTH_VAL}
    ports:
    - ${DOCRIVER_OPENTEL_GRPC_PORT:-4317}:4317
    - ${DOCRIVER_OPENTEL_HTTP_PORT:-4318}:4318
    - ${DOCRIVER_OPENTEL_UX_PORT:-55679}:55679
    command: [
      "--config", "/etc/otelcol/config.yaml", "--feature-gates=-component.UseLocalHostAsDefaultHost"
    ]
